#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-syncthing.json" ] && {
    cat > /usr/share/ucitrack/luci-app-syncthing.json << EEOF
{
    "config": "syncthing",
    "init": "syncthing"
}
EEOF
}
touch /etc/config/syncthing

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@syncthing[-1]
	add ucitrack syncthing
	set ucitrack.@syncthing[-1].exec='/etc/init.d/syncthing restart'
	commit ucitrack
EOF
# remove LuCI cache
rm -f /tmp/luci*
exit 0
