#!/bin/sh
# One-time firewall3 rules for IKEv2 when iptables is used.
set -e

add_rule() {
    local name="$1"
    uci -q show firewall | grep -q "firewall\..*\.name='$name'" && return 0
    uci -q add firewall rule >/dev/null
    uci -q set firewall.@rule[-1].name="$name"
    shift
    while [ "$#" -gt 1 ]; do
        local key="$1"; local val="$2"; shift 2
        uci -q set firewall.@rule[-1].$key="$val"
    done
}

# 入站 IKE/ESP
add_rule "Allow-IPsec-IKE" src 'wan' proto 'udp' dest_port '500' target 'ACCEPT' family 'any'
add_rule "Allow-IPsec-NAT-T" src 'wan' proto 'udp' dest_port '4500' target 'ACCEPT' family 'any'
add_rule "Allow-IPsec-ESP" src 'wan' proto 'esp' target 'ACCEPT' family 'any'

# 基于 policy 的转发许可（入方向/出方向）
add_rule "Allow-IPsec-Policy-In" src '*' proto 'all' family 'any' target 'ACCEPT' extra '-m policy --pol ipsec --dir in'
add_rule "Allow-IPsec-Policy-Out" src '*' proto 'all' family 'any' target 'ACCEPT' extra '-m policy --pol ipsec --dir out'

# 显式允许 IPsec 客户端访问 LAN / 访问外网（WAN）
add_rule "Allow-IPsec-to-LAN" src '*' dest 'lan' proto 'all' target 'ACCEPT' family 'any' extra '-m policy --pol ipsec --dir in'
add_rule "Allow-IPsec-to-WAN" src '*' dest 'wan' proto 'all' target 'ACCEPT' family 'any' extra '-m policy --pol ipsec --dir in'

uci -q commit firewall
[ -x /etc/init.d/firewall ] && /etc/init.d/firewall reload || true
