#!/bin/sh
# uci-defaults: initial firewall + hints for IPsec IKEv2 (iptables/firewall3)
set -e

add_rule() {
    local name="$1"
    uci -q show firewall | grep -q "firewall\..*\.name='$name'" && return 0
    uci -q add firewall rule >/dev/null
    uci -q set firewall.@rule[-1].name="$name"
    shift
    while [ "$#" -gt 1 ]; do
        local key="$1"; local val="$2"; shift 2
        uci -q set firewall.@rule[-1].$key="$val"
    done
}

# Inbound IKE/ESP
add_rule "Allow-IPsec-IKE" src 'wan' proto 'udp' dest_port '500' target 'ACCEPT'
add_rule "Allow-IPsec-NAT-T" src 'wan' proto 'udp' dest_port '4500' target 'ACCEPT'
add_rule "Allow-IPsec-ESP" src 'wan' proto 'esp' target 'ACCEPT'

# Policy accept
add_rule "Allow-IPsec-Policy-In"  src '*' proto 'all' target 'ACCEPT' extra '-m policy --pol ipsec --dir in'
add_rule "Allow-IPsec-Policy-Out" src '*' proto 'all' target 'ACCEPT' extra '-m policy --pol ipsec --dir out'

# Access to LAN and Internet (WAN) from IPsec clients
add_rule "Allow-IPsec-to-LAN" src '*' dest 'lan' proto 'all' target 'ACCEPT' extra '-m policy --pol ipsec --dir in'
add_rule "Allow-IPsec-to-WAN" src '*' dest 'wan' proto 'all' target 'ACCEPT' extra '-m policy --pol ipsec --dir in'

uci -q commit firewall

# Mark as applied
rm -f /etc/uci-defaults/luci-app-ipsec-ikev2
