#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-gecoosac.json" ] && {
    cat > /usr/share/ucitrack/luci-app-gecoosac.json << EEOF
{
    "config": "gecoosac",
    "init": "gecoosac"
}
EEOF
}

while uci -q delete 'ucitrack.@gecoosac[0]'; do
	:
done

uci -q batch <<-EOF >/dev/null
	add ucitrack gecoosac
	set ucitrack.@gecoosac[-1].init=gecoosac
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache
exit 0
