#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-get.json" ] && {
    cat > /usr/share/ucitrack/luci-app-get.json << EEOF
{
    "config": "get",
    "init": "get"
}
EEOF
}

uci -q get ucitrack.@dynv6[0] || uci add ucitrack dynv6
uci set ucitrack.@dynv6[0]=dynv6
uci set ucitrack.@dynv6[0].exec="/bin/sh /etc/rc.common /etc/init.d/dynv6 restart"
uci commit ucitrack
/etc/init.d/ucitrack restart

exit 0
