#!/bin/sh /etc/rc.common

USE_PROCD=1

boot() {
    return 0
}

start_service() {
    procd_open_instance
    procd_set_param command /usr/libexec/rtbwmon.sh gc
    procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger ""
}
