#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-hotplug.json" ] && {
    cat > /usr/share/ucitrack/luci-app-hotplug.json << EEOF
{
    "config": "hotplug",
    "init": "hotplug"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@hotplug[-1]
	add ucitrack hotplug
	set ucitrack.@hotplug[-1].init=hotplug
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
