#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-luci_app_control_webrestriction.json" ] && {
    cat > /usr/share/ucitrack/luci-app-luci_app_control_webrestriction.json << EEOF
{
    "config": "luci_app_control_webrestriction",
    "init": "luci_app_control_webrestriction"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci_app_control_webrestriction[-1]
	add ucitrack luci_app_control_webrestriction
	set ucitrack.@luci_app_control_webrestriction[-1].init=luci-app-control-webrestriction
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
exit 0
