#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-snmpd.json" ] && {
    cat > /usr/share/ucitrack/luci-app-snmpd.json << EEOF
{
    "config": "snmpd",
    "init": "snmpd"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@snmpd[-1]
	add ucitrack snmpd
	set ucitrack.@snmpd[-1].init=snmpd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
