#!/bin/sh /etc/rc.common

START=99

CONFIG="luci-app-ipsec-server"
IPSEC_SECRETS_FILE=/etc/ipsec.secrets
IPSEC_CONN_FILE=/etc/ipsec.conf
IPSEC_CERT_DIR=/etc/ipsec.d
IPSEC_CERTS_DIR=${IPSEC_CERT_DIR}/certs
IPSEC_CACERTS_DIR=${IPSEC_CERT_DIR}/cacerts
IPSEC_PRIVATE_DIR=${IPSEC_CERT_DIR}/private
ACME_CERT_DIR=/etc/ssl/acme
IKEV2_EAP_SERVER_CERT=${IPSEC_CERTS_DIR}/ikev2-eap-server-cert.pem
IKEV2_EAP_SERVER_CHAIN=${IPSEC_CACERTS_DIR}/ikev2-eap-chain.pem
IKEV2_EAP_SERVER_KEY=${IPSEC_PRIVATE_DIR}/ikev2-eap-server-key.pem
LEGACY_L2TP_PATH=/var/etc/xl2tpd

vt_clientip=$(uci -q get ${CONFIG}.@service[0].clientip)

ipt_flag="IPSec VPN Server"

log() {
	logger -t "${CONFIG}" "$*"
}

ipsec_escape() {
	printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

prepare_ikev2_eap_acme_certificates() {
	local acme_name="$1"
	local cert_file
	local fullchain_file
	local chain_file
	local key_file

	[ -n "${acme_name}" ] || return 1

	cert_file="${ACME_CERT_DIR}/${acme_name}.crt"
	fullchain_file="${ACME_CERT_DIR}/${acme_name}.fullchain.crt"
	chain_file="${ACME_CERT_DIR}/${acme_name}.chain.crt"
	key_file="${ACME_CERT_DIR}/${acme_name}.key"

	[ -s "${cert_file}" ] || cert_file="${fullchain_file}"

	if [ ! -s "${cert_file}" ] || [ ! -s "${key_file}" ]; then
		log "ACME certificate files for ${acme_name} were not found under ${ACME_CERT_DIR}; configure luci-app-acme and run /etc/init.d/acme renew first"
		return 1
	fi

	mkdir -p ${IPSEC_CERTS_DIR} ${IPSEC_CACERTS_DIR} ${IPSEC_PRIVATE_DIR}
	ln -sfn "${cert_file}" ${IKEV2_EAP_SERVER_CERT} || return 1
	ln -sfn "${key_file}" ${IKEV2_EAP_SERVER_KEY} || return 1

	if [ -s "${chain_file}" ]; then
		ln -sfn "${chain_file}" ${IKEV2_EAP_SERVER_CHAIN} || return 1
	else
		rm -f ${IKEV2_EAP_SERVER_CHAIN}
	fi

	return 0
}

get_enabled_anonymous_secs() {
	uci -q show "${CONFIG}" | grep "${1}\[.*\.enabled='1'" | cut -d '.' -sf2
}

ipt_rule() {
	if [ "$1" = "add" ]; then
		iptables -t nat -I POSTROUTING -s ${vt_clientip} -m comment --comment "${ipt_flag}" -j MASQUERADE 2>/dev/null
		iptables -I forwarding_rule -s ${vt_clientip} -m comment --comment "${ipt_flag}" -j ACCEPT 2>/dev/null
		iptables -I forwarding_rule -m policy --dir in --pol ipsec --proto esp -m comment --comment "${ipt_flag}" -j ACCEPT 2>/dev/null
		iptables -I forwarding_rule -m policy --dir out --pol ipsec --proto esp -m comment --comment "${ipt_flag}" -j ACCEPT 2>/dev/null
		iptables -I INPUT -p udp -m multiport --dports 500,4500 -m comment --comment "${ipt_flag}" -j ACCEPT 2>/dev/null
		iptables -I INPUT -p esp -m comment --comment "${ipt_flag}" -j ACCEPT 2>/dev/null
		iptables -t mangle -I OUTPUT -p udp -m multiport --sports 500,4500 -m comment --comment "${ipt_flag}" -j RETURN 2>/dev/null
	else
		ipt_del() {
			for i in $(seq 1 $($1 -nL $2 | grep -c "${ipt_flag}")); do
				local index=$($1 --line-number -nL $2 | grep "${ipt_flag}" | head -1 | awk '{print $1}')
				$1 -w -D $2 $index 2>/dev/null
			done
		}
		ipt_del "iptables" "forwarding_rule"
		ipt_del "iptables" "INPUT"
		ipt_del "iptables -t nat" "POSTROUTING"
		ipt_del "iptables -t mangle" "OUTPUT"
	fi
}

gen_include() {
	echo '#!/bin/sh' > /var/etc/ipsecvpn.include
	extract_rules() {
		echo "*$1"
		iptables-save -t $1 | grep "${ipt_flag}" | \
		sed -e "s/^-A \(INPUT\)/-I \1 1/"
		echo 'COMMIT'
	}
	cat <<-EOF2 >> /var/etc/ipsecvpn.include
		iptables-save -c | grep -v "${ipt_flag}" | iptables-restore -c
		iptables-restore -n <<-EOT
		$(extract_rules filter)
		$(extract_rules nat)
		EOT
	EOF2
	return 0
}

start() {
	local vt_enabled=$(uci -q get ${CONFIG}.@service[0].enabled)
	[ "$vt_enabled" = 0 ] && return 1

	local vt_gateway="${vt_clientip%.*}.1"
	local vt_secret=$(uci -q get ${CONFIG}.@service[0].secret)
	local vt_secret_escaped=$(ipsec_escape "${vt_secret}")
	local ikev2_psk_enable=$(uci -q get ${CONFIG}.@service[0].ikev2_psk_enable)
	local ikev2_eap_enable=$(uci -q get ${CONFIG}.@service[0].ikev2_eap_enable)
	local ikev2_eap_id=$(uci -q get ${CONFIG}.@service[0].ikev2_eap_id)
	local ikev2_eap_acme_name=$(uci -q get ${CONFIG}.@service[0].ikev2_eap_acme_name)
	local ikev2_eap_ready=0
	local ipsec_ikev2_psk_config=""
	local ipsec_ikev2_eap_config=""
	local ipsec_extra_secrets=""

	[ -n "${ikev2_psk_enable}" ] || ikev2_psk_enable=0
	[ -n "${ikev2_eap_enable}" ] || ikev2_eap_enable=0
	[ -n "${ikev2_eap_acme_name}" ] || ikev2_eap_acme_name="${ikev2_eap_id}"

	if [ "${ikev2_psk_enable}" = 1 ]; then
		ipsec_ikev2_psk_config=$(cat <<-EOF2
		#######################################
		# IKEv2 Connections
		#######################################

		conn IKEv2-PSK
		  also=RemoteAccess
		  keyexchange=ikev2
		  fragmentation=yes
		  forceencaps=yes
		  ike=aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048,3des-sha1-modp1024
		  esp=aes256-sha1,aes128-sha1,aes256-sha256,aes128-sha256,3des-sha1
		  leftauth=psk
		  rightauth=psk
		EOF2
		)
	fi

	if [ "${ikev2_eap_enable}" = 1 ]; then
		if [ -z "${ikev2_eap_id}" ]; then
			log "IKEv2 EAP is enabled but the server ID is empty, skipping IKEv2 EAP"
		elif prepare_ikev2_eap_acme_certificates "${ikev2_eap_acme_name}"; then
			ikev2_eap_ready=1
			ipsec_extra_secrets=$(cat <<-EOF2
		: RSA ikev2-eap-server-key.pem
		EOF2
			)
			ipsec_ikev2_eap_config=$(cat <<-EOF2

		conn IKEv2-EAP
		  also=RemoteAccess
		  keyexchange=ikev2
		  fragmentation=yes
		  forceencaps=yes
		  ike=aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048,3des-sha1-modp1024
		  esp=aes256-sha1,aes128-sha1,aes256-sha256,aes128-sha256,3des-sha1
		  leftauth=pubkey
		  leftid=${ikev2_eap_id}
		  leftcert=ikev2-eap-server-cert.pem
		  leftsendcert=always
		  rightauth=eap-mschapv2
		  eap_identity=%identity
		EOF2
			)
		else
			log "Failed to prepare IKEv2 EAP ACME certificate links, skipping IKEv2 EAP"
		fi
	fi

	cat > ${IPSEC_CONN_FILE} <<-EOF2
		# ipsec.conf - strongSwan IPsec configuration file

		config setup
		  uniqueids=no
		  charondebug="cfg 2, dmn 2, ike 2, net 0"

		conn %default
		  dpdaction=clear
		  dpddelay=300s
		  rekey=no
		  left=%defaultroute
		  leftfirewall=yes
		  right=%any
		  ikelifetime=60m
		  keylife=20m
		  rekeymargin=3m
		  keyingtries=1
		  auto=add

		#######################################
		# Remote Access Connections
		#######################################

		conn RemoteAccess
		  leftsubnet=0.0.0.0/0
		  rightsubnet=${vt_clientip}
		  rightsourceip=${vt_clientip}
		  rightdns=${vt_gateway}
		  ike=aes256-sha256-modp2048,aes128-sha256-modp2048,aes128-sha1-modp2048,aes128-sha1-modp1024,3des-sha1-modp1024,3des-sha1-modp1536
		  esp=aes256-sha256,aes128-sha256,aes128-sha1,3des-sha1

		# Cisco IPSec
		conn IKEv1-PSK-XAuth
		  also=RemoteAccess
		  keyexchange=ikev1
		  leftauth=psk
		  rightauth=psk
		  rightauth2=xauth

		${ipsec_ikev2_psk_config}${ipsec_ikev2_eap_config}
	EOF2

	cat > ${IPSEC_SECRETS_FILE} <<-EOF2
	# /etc/ipsec.secrets - strongSwan IPsec secrets file
	: PSK "${vt_secret_escaped}"
	${ipsec_extra_secrets}
	EOF2

	local ipsec_users=$(get_enabled_anonymous_secs "@ipsec_users")
	[ -n "${ipsec_users}" ] && {
		for _user in ${ipsec_users}; do
			local u_enabled=$(uci -q get ${CONFIG}.${_user}.enabled)
			[ "${u_enabled}" -eq 1 ] || continue

			local u_username=$(uci -q get ${CONFIG}.${_user}.username)
			[ -n "${u_username}" ] || continue

			local u_password=$(uci -q get ${CONFIG}.${_user}.password)
			[ -n "${u_password}" ] || continue

			local u_password_escaped=$(ipsec_escape "${u_password}")
			printf '%s : XAUTH "%s"\n' "${u_username}" "${u_password_escaped}" >> ${IPSEC_SECRETS_FILE}
			[ "${ikev2_eap_ready}" = 1 ] && printf '%s : EAP "%s"\n' "${u_username}" "${u_password_escaped}" >> ${IPSEC_SECRETS_FILE}
		done
	}
	unset user

	ipt_rule add

	/usr/lib/ipsec/starter --daemon charon --nofork > /dev/null 2>&1 &
	gen_include

	uci -q batch <<-EOF2 >/dev/null
		set network.ipsec_server.ipaddr="${vt_clientip%.*}.1"
		commit network
	EOF2
	ifup ipsec_server > /dev/null 2>&1
}

stop() {
	ifdown ipsec_server > /dev/null 2>&1
	top -bn1 | grep "${LEGACY_L2TP_PATH}" | grep -v "grep" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	rm -rf ${LEGACY_L2TP_PATH}
	ps -w | grep "/usr/lib/ipsec" | grep -v "grep" | awk '{print $1}' | xargs kill -9 >/dev/null 2>&1
	ipt_rule del
	rm -rf /var/etc/ipsecvpn.include
}

gen_iface_and_firewall() {
	uci -q batch <<-EOF2 >/dev/null
		delete network.ipsec_server
		set network.ipsec_server=interface
		set network.ipsec_server.device="ipsec0"
		set network.ipsec_server.device="ipsec0"
		set network.ipsec_server.proto="static"
		set network.ipsec_server.ipaddr="${vt_clientip%.*}.1"
		set network.ipsec_server.netmask="255.255.255.0"
		commit network

		delete firewall.ipsecserver
		set firewall.ipsecserver=zone
		set firewall.ipsecserver.name="ipsecserver"
		set firewall.ipsecserver.input="ACCEPT"
		set firewall.ipsecserver.forward="ACCEPT"
		set firewall.ipsecserver.output="ACCEPT"
		set firewall.ipsecserver.network="ipsec_server"
		commit firewall
	EOF2
}

if [ -z "$(uci -q get network.ipsec_server)" ] || [ -z "$(uci -q get firewall.ipsecserver)" ]; then
	gen_iface_and_firewall
fi
