#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-powersupply.json" ] && {
    cat > /usr/share/ucitrack/luci-app-powersupply.json << EEOF
{
    "config": "powersupply",
    "init": "powersupply"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@powersupply[-1]
	add ucitrack powersupply
	set ucitrack.@powersupply[-1].init=powersupply
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
