#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete firewall.v2ray_server
	set firewall.v2ray_server=include
	set firewall.v2ray_server.type=script
	set firewall.v2ray_server.path=/var/etc/v2ray_server.include
	set firewall.v2ray_server.reload=1
	commit firewall
EOF

uci -q batch <<-EOF >/dev/null
EOF

rm -rf /tmp/luci-*cache
exit 0
