#!/bin/sh

[ "$ACTION" = "issued" ] || [ "$ACTION" = "renewed" ] || exit 0

CONFIG="luci-app-ipsec-server"
SERVICE_ENABLED=$(uci -q get ${CONFIG}.@service[0].enabled)
IKEV2_EAP_ENABLED=$(uci -q get ${CONFIG}.@service[0].ikev2_eap_enable)

[ "$SERVICE_ENABLED" = "1" ] || exit 0
[ "$IKEV2_EAP_ENABLED" = "1" ] || exit 0

logger -t ${CONFIG} "ACME certificate event ${ACTION} detected, restarting IPSec VPN Server"
/etc/init.d/luci-app-ipsec-server restart >/dev/null 2>&1 &
