#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-smscontrol.json" ] && {
    cat > /usr/share/ucitrack/luci-app-smscontrol.json << EEOF
{
    "config": "smscontrol",
    "init": "smscontrol"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@smscontrol[-1]
	add ucitrack smscontrol
	set ucitrack.@smscontrol[-1].init=smscontrol
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
