#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-nfs.json" ] && {
    cat > /usr/share/ucitrack/luci-app-nfs.json << EEOF
{
    "config": "nfs",
    "init": "nfs"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@nfs[-1]
	add ucitrack nfs
	set ucitrack.@nfs[-1].init=nfs
	commit ucitrack
EOF

/etc/init.d/nfs enable && /etc/init.d/nfs restart

rm -f /tmp/luci-indexcache

exit 0
