#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-baidupcs-web.json" ] && {
    cat > /usr/share/ucitrack/luci-app-baidupcs-web.json << EEOF
{
    "config": "baidupcs-web",
    "init": "baidupcs-web"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@baidupcs-web[-1]
	add ucitrack baidupcs-web
	set ucitrack.@baidupcs-web[-1].init=baidupcs-web
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
