#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-autoreboot.json" ] && {
    cat > /usr/share/ucitrack/luci-app-autoreboot.json << EEOF
{
    "config": "autoreboot",
    "init": "autoreboot"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@autoreboot[-1]
	add ucitrack autoreboot
	set ucitrack.@autoreboot[-1].init=autoreboot
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
