#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-aliyundrive-fuse.json" ] && {
    cat > /usr/share/ucitrack/luci-app-aliyundrive-fuse.json << EEOF
{
    "config": "aliyundrive-fuse",
    "init": "aliyundrive-fuse"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@aliyundrive-fuse[-1]
	add ucitrack aliyundrive-fuse
	set ucitrack.@aliyundrive-fuse[-1].init=aliyundrive-fuse
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
