#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-luci-app-ipsec-server.json" ] && {
    cat > /usr/share/ucitrack/luci-app-luci-app-ipsec-server.json << EEOF
{
    "config": "luci-app-ipsec-server",
    "init": "luci-app-ipsec-server"
}
EEOF
}

uci -q batch <<-EOF2 >/dev/null
	delete firewall.luci_app_ipsec_server
	set firewall.luci_app_ipsec_server=include
	set firewall.luci_app_ipsec_server.type=script
	set firewall.luci_app_ipsec_server.path=/var/etc/ipsecvpn.include
	set firewall.luci_app_ipsec_server.reload=1
EOF2

uci -q batch <<-EOF2 >/dev/null
	delete ucitrack.@luci-app-ipsec-server[-1]
	add ucitrack luci-app-ipsec-server
	set ucitrack.@luci-app-ipsec-server[-1].init=luci-app-ipsec-server
	commit ucitrack
EOF2

uci -q delete luci-app-ipsec-server.@service[0].l2tp_enable
uci -q delete luci-app-ipsec-server.@service[0].l2tp_localip
uci -q delete luci-app-ipsec-server.@service[0].l2tp_remoteip
uci -q set luci-app-ipsec-server.@service[0].ikev2_ipv6_enable='1'
[ -n "$(uci -q get luci-app-ipsec-server.@service[0].clientip6)" ] || \
	uci -q set luci-app-ipsec-server.@service[0].clientip6='fd42:42:42::10/120'
while uci -q delete luci-app-ipsec-server.@l2tp_users[0] >/dev/null 2>&1; do :; done
uci -q commit luci-app-ipsec-server

/etc/init.d/ipsec disable 2>/dev/null
/etc/init.d/ipsec stop 2>/dev/null
/etc/init.d/xl2tpd disable 2>/dev/null
/etc/init.d/xl2tpd stop 2>/dev/null

rm -f /usr/lib/lua/luci/model/cbi/ipsec-server/l2tp_user.lua
rm -f /usr/lib/lua/luci/model/cbi/ipsec-server/online.lua
rm -rf /usr/share/xl2tpd
rm -rf /tmp/luci-*cache
exit 0
