#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-luci-app-ipsec-server.json" ] && {
    cat > /usr/share/ucitrack/luci-app-luci-app-ipsec-server.json << EEOF
{
    "config": "luci-app-ipsec-server",
    "init": "luci-app-ipsec-server"
}
EEOF
}
[ ! -f "/usr/share/ucitrack/luci-app-luci-app-ipsec-server.json" ] && {
    cat > /usr/share/ucitrack/luci-app-luci-app-ipsec-server.json << EEOF
{
    "config": "luci-app-ipsec-server",
    "init": "luci-app-ipsec-server"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete firewall.luci_app_ipsec_server
	set firewall.luci_app_ipsec_server=include
	set firewall.luci_app_ipsec_server.type=script
	set firewall.luci_app_ipsec_server.path=/var/etc/ipsecvpn.include
	set firewall.luci_app_ipsec_server.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci-app-ipsec-server[-1]
	add ucitrack luci-app-ipsec-server
	set ucitrack.@luci-app-ipsec-server[-1].init=luci-app-ipsec-server
	commit ucitrack
EOF

uci -q batch <<-EOF >/dev/null
	delete luci-app-ipsec-server.@service[0].l2tp_enable
	delete luci-app-ipsec-server.@service[0].l2tp_localip
	delete luci-app-ipsec-server.@service[0].l2tp_remoteip
	commit luci-app-ipsec-server
EOF

while uci -q delete luci-app-ipsec-server.@l2tp_users[0] >/dev/null 2>&1; do
	uci -q commit luci-app-ipsec-server
done

/etc/init.d/ipsec disable 2>/dev/null
/etc/init.d/ipsec stop 2>/dev/null
rm -rf /tmp/luci-*cache
exit 0
