#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-qbittorrent.json" ] && {
    cat > /usr/share/ucitrack/luci-app-qbittorrent.json << EEOF
{
    "config": "qbittorrent",
    "init": "qbittorrent"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@qbittorrent[-1]
	add ucitrack qbittorrent
	set ucitrack.@qbittorrent[-1].init=qbittorrent
	commit ucitrack
EOF

mkdir /opt

rm -f /tmp/luci-indexcache*
exit 0
