name: Sync Datfiles

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download latest datfiles
        run: |
          rm -rf datfiles
          mkdir -p datfiles
          cd datfiles
          
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/country-lite.mmdb
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/country.mmdb
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geoip-lite.dat
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geoip-lite.db
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geoip-lite.metadb
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geoip.dat
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geosite.dat
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geosite.db
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geosite-lite.dat
          wget -q https://github.com/rtaserver/meta-rules-dat/releases/latest/download/geosite-lite.db
          
      - name: Commit dan Push perubahan
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add datfiles/
          git commit -m "Update datfiles $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
          git push origin main