#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-luci_statistics.json" ] && {
    cat > /usr/share/ucitrack/luci-app-luci_statistics.json << EEOF
{
    "config": "luci_statistics",
    "init": "luci_statistics"
}
EEOF
}

# register commit handler
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@luci_statistics[-1]
	add ucitrack luci_statistics
	set ucitrack.@luci_statistics[-1].init=luci_statistics
	commit ucitrack
EOF

exit 0
