#!/bin/sh

uci -q batch <<-EOF >/dev/null
EOF

[ ! -s '/etc/config/cqustdotnet' ] && cp -f /usr/share/cqustdotnet/0_default_config /etc/config/cqustdotnet
rm -f /tmp/luci-indexcache
rm -rf /tmp/luci-modulecache/
exit 0
